
all:
	cd cmdlib && $(MAKE)
	cd container && $(MAKE)
	cd ddslib && $(MAKE)
	cd debugging && $(MAKE)
	cd etclib && $(MAKE)
	cd filematch && $(MAKE)
	cd generic && $(MAKE)
	cd gtkutil && $(MAKE)
	cd l_net && $(MAKE)
	cd math && $(MAKE)
	cd mathlib && $(MAKE)
	#cd md5lib && $(MAKE)
	cd memory && $(MAKE)
	cd modulesystem && $(MAKE)
	cd os && $(MAKE)
	cd picomodel && $(MAKE)
	cd profile && $(MAKE)
	cd script && $(MAKE)
	cd signal && $(MAKE)
	cd splines && $(MAKE)
	cd stream && $(MAKE)
	cd string && $(MAKE)
	cd uilib && $(MAKE)
	cd xml && $(MAKE)

clean:
	cd cmdlib && $(MAKE) clean
	cd container && $(MAKE) clean
	cd ddslib && $(MAKE) clean
	cd debugging && $(MAKE) clean
	cd etclib && $(MAKE) clean
	cd filematch && $(MAKE) clean
	cd generic && $(MAKE) clean
	cd gtkutil && $(MAKE) clean
	cd l_net && $(MAKE) clean
	cd math && $(MAKE) clean
	cd mathlib && $(MAKE) clean
	#cd md5lib && $(MAKE) clean
	cd memory && $(MAKE) clean
	cd modulesystem && $(MAKE) clean
	cd os && $(MAKE) clean
	cd picomodel && $(MAKE) clean
	cd profile && $(MAKE) clean
	cd script && $(MAKE) clean
	cd signal && $(MAKE) clean
	cd splines && $(MAKE) clean
	cd stream && $(MAKE) clean
	cd string && $(MAKE) clean
	cd uilib && $(MAKE) clean
	cd xml && $(MAKE) clean
